/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UtcTimestamp = string;

export interface SeasonPayload {
  schemaVersion: 1;
  generatedAt: UtcTimestamp;
  freshness: "fresh" | "stale" | "delayed" | "unavailable";
  season: number;
  currentRound: number | null;
  nextRound: number | null;
  /**
   * @minItems 1
   */
  events: [SeasonEvent, ...SeasonEvent[]];
  driverStandings: DriverStanding[];
  constructorStandings: ConstructorStanding[];
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}
export interface SeasonEvent {
  round: number;
  slug: string;
  raceName: string;
  startsAt: UtcTimestamp;
  state: "scheduled" | "provisional" | "complete" | "delayed" | "unavailable";
  circuit: Circuit;
  sessions: Session[];
  qualifyingClassification: QualifyingClassification | null;
  raceClassification: RaceClassification | null;
}
export interface Circuit {
  id: string;
  name: string;
  locality: string;
  country: string;
  latitude: number;
  longitude: number;
}
export interface Session {
  key: string;
  name: string;
  startsAt: UtcTimestamp;
  state: "scheduled" | "provisional" | "complete" | "delayed" | "unavailable";
}
export interface QualifyingClassification {
  sessionKey: "qualifying";
  rows: QualifyingRow[];
}
export interface QualifyingRow {
  position: number;
  driverCode: string;
  driverName: string;
  constructorName: string;
  q1: string | null;
  q2: string | null;
  q3: string | null;
}
export interface RaceClassification {
  sessionKey: "race";
  rows: RaceRow[];
}
export interface RaceRow {
  position: number;
  driverCode: string;
  driverName: string;
  constructorName: string;
  laps: number;
  status: string;
  points: number;
  time: string | null;
  fastestLap: string | null;
}
export interface DriverStanding {
  position: number;
  name: string;
  code: string;
  points: number;
  wins: number;
}
export interface ConstructorStanding {
  position: number;
  name: string;
  points: number;
  wins: number;
}
export interface Source {
  name: string;
  url: string;
  fetchedAt: UtcTimestamp;
}
