/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UtcTimestamp = string;
export type Classification = QualifyingClassification | RaceClassification;

export interface WeekendPayload {
  schemaVersion: 1;
  generatedAt: UtcTimestamp;
  freshness: "fresh" | "stale" | "delayed" | "unavailable";
  event: Event;
  sessions: Session[];
  classifications: Classification[];
  driverStandings: DriverStanding[];
  constructorStandings: ConstructorStanding[];
  history: HistoryEntry[];
  seasonSchedule: ScheduleEntry[];
  sources: Source[];
}
export interface Event {
  season: number;
  round: number;
  slug: string;
  raceName: string;
  startsAt: UtcTimestamp;
  circuit: Circuit;
}
export interface Circuit {
  id: string;
  name: string;
  locality: string;
  country: string;
  latitude: number;
  longitude: number;
}
export interface Session {
  key: string;
  name: string;
  startsAt: UtcTimestamp;
  state: "scheduled" | "provisional" | "complete" | "delayed" | "unavailable";
}
export interface QualifyingClassification {
  sessionKey: "qualifying";
  rows: QualifyingRow[];
}
export interface QualifyingRow {
  position: number;
  driverCode: string;
  driverName: string;
  constructorName: string;
  q1: string | null;
  q2: string | null;
  q3: string | null;
}
export interface RaceClassification {
  sessionKey: "race";
  rows: RaceRow[];
}
export interface RaceRow {
  position: number;
  driverCode: string;
  driverName: string;
  constructorName: string;
  laps: number;
  status: string;
  points: number;
  time: string | null;
  fastestLap: string | null;
}
export interface DriverStanding {
  position: number;
  name: string;
  code: string;
  points: number;
  wins: number;
}
export interface ConstructorStanding {
  position: number;
  name: string;
  points: number;
  wins: number;
}
export interface HistoryEntry {
  season: number;
  round: number;
  raceName: string;
  winnerName: string;
  winnerConstructor: string;
}
export interface ScheduleEntry {
  round: number;
  raceName: string;
  slug: string;
  startsAt: UtcTimestamp;
  circuitName: string;
  country: string;
}
export interface Source {
  name: string;
  url: string;
  fetchedAt: UtcTimestamp;
}
